name: Matthew Rothenberg

timezone: America/New_York
markdown: kramdown

gems:
  - jemoji

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /:year/:title
